# Generated by Django 5.2.6 on 2025-10-02 10:40

import apps.files.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., container_image)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "allowed_mime_types",
                    models.JSONField(
                        default=list,
                        help_text='Allowed MIME types: ["image/jpeg", "application/pdf"]',
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=10, help_text="Maximum file size in MB"
                    ),
                ),
            ],
            options={
                "verbose_name": "File Category",
                "verbose_name_plural": "File Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=apps.files.utils.generate_file_path
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from upload", max_length=255
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="Detected MIME type", max_length=100),
                ),
                ("size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Whether file is publicly accessible"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Soft delete flag"
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="files.filecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "attachment_type",
                    models.CharField(
                        help_text="Type of attachment (e.g., primary, supporting, damage_evidence)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of what this attachment shows/contains",
                        max_length=500,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for displaying multiple attachments"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Attachment",
                "verbose_name_plural": "File Attachments",
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="files_filea_content_8d7b94_idx",
                    ),
                    models.Index(
                        fields=["attachment_type"],
                        name="files_filea_attachm_2c1159_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["-created_at"], name="files_file_created_7795e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_category", "-created_at"],
                name="files_file_file_ca_bbcdbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="files_file_uploade_1be14c_idx",
            ),
        ),
    ]
