# Generated by Django 5.2.6 on 2025-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.AlterModelOptions(
            name="fileattachment",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "Вложенный файл",
                "verbose_name_plural": "Вложенные файлы",
            },
        ),
        migrations.AlterModelOptions(
            name="filecategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория файла",
                "verbose_name_plural": "Категории файлов",
            },
        ),
        migrations.AlterField(
            model_name="file",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Флаг мягкого удаления"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Доступен ли файл публично"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="mime_type",
            field=models.CharField(help_text="Определённый MIME тип", max_length=100),
        ),
        migrations.AlterField(
            model_name="file",
            name="original_filename",
            field=models.CharField(
                help_text="Исходное имя файла при загрузке", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(help_text="Размер файла в байтах"),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="attachment_type",
            field=models.CharField(
                help_text="Тип вложения (например, основной, дополнительный, доказательство повреждения)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Необязательное описание содержимого вложения",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Порядок отображения нескольких вложений"
            ),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="allowed_mime_types",
            field=models.JSONField(
                default=list,
                help_text='Разрешённые MIME типы: ["image/jpeg", "application/pdf"]',
            ),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="code",
            field=models.CharField(
                help_text="Уникальный код (например, container_image)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="max_file_size_mb",
            field=models.IntegerField(
                default=10, help_text="Максимальный размер файла в МБ"
            ),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="name",
            field=models.CharField(help_text="Отображаемое название", max_length=100),
        ),
    ]
