# Generated by Django 5.2.6 on 2026-02-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_alter_destination_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANPRDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('plate_number', models.CharField(db_index=True, help_text='Распознанный номерной знак', max_length=20, verbose_name='номер ТС')),
                ('confidence', models.IntegerField(default=0, help_text='Уверенность камеры в распознавании (0-100)', verbose_name='уверенность')),
                ('direction', models.CharField(choices=[('approach', 'Приближение'), ('depart', 'Отъезд'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='направление')),
                ('vehicle_type', models.CharField(blank=True, default='', help_text='Тип ТС от камеры (truck, car, etc.)', max_length=50, verbose_name='тип ТС')),
                ('country', models.CharField(blank=True, default='', max_length=10, verbose_name='страна')),
                ('plate_color', models.CharField(blank=True, default='', max_length=20, verbose_name='цвет номера')),
                ('camera_timestamp', models.DateTimeField(blank=True, help_text='Время события по часам камеры', null=True, verbose_name='время камеры')),
                ('raw_event_type', models.CharField(blank=True, default='', help_text='Тип события камеры (ANPR, etc.)', max_length=50, verbose_name='тип события')),
                ('gate_id', models.CharField(db_index=True, default='main', max_length=50, verbose_name='ворота')),
                ('matched_entry', models.ForeignKey(blank=True, help_text='Автоматически найденный VehicleEntry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anpr_detections', to='vehicles.vehicleentry', verbose_name='сопоставленный въезд')),
            ],
            options={
                'verbose_name': 'ANPR детекция',
                'verbose_name_plural': 'ANPR детекции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate_number', '-created_at'], name='gate_anprde_plate_n_50835b_idx'), models.Index(fields=['gate_id', '-created_at'], name='gate_anprde_gate_id_58a200_idx')],
            },
        ),
    ]
