# Generated by Django 5.2.6 on 2026-01-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('manager', 'Менеджер'), ('customer', 'Клиент')], max_length=20)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('container_entry_created', 'Контейнер добавлен'), ('container_exit_recorded', 'Выезд контейнера'), ('crane_operation_added', 'Крановая операция'), ('preorder_created', 'Заявка создана'), ('preorder_cancelled', 'Заявка отменена')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог активности Telegram',
                'verbose_name_plural': 'Логи активности Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='core_telegr_action_96ac7f_idx'), models.Index(fields=['user', '-created_at'], name='core_telegr_user_id_9d622f_idx'), models.Index(fields=['user_type', '-created_at'], name='core_telegr_user_ty_87128d_idx'), models.Index(fields=['-created_at'], name='core_telegr_created_b0fa68_idx')],
            },
        ),
    ]
