# Generated by Django 5.2.6 on 2026-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_telegram_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramactivitylog',
            name='group_notification_error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка уведомления группы'),
        ),
        migrations.AddField(
            model_name='telegramactivitylog',
            name='group_notification_status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('error', 'Ошибка'), ('not_applicable', 'Не применимо')], default='not_applicable', max_length=20, verbose_name='Статус уведомления группы'),
        ),
        migrations.AlterField(
            model_name='telegramactivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='telegramactivitylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
