# Generated by Django 5.2.6 on 2026-02-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_group_notification_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramactivitylog',
            name='group_chat_id',
            field=models.CharField(blank=True, default='', help_text='Telegram chat_id where notification was sent', max_length=50, verbose_name='ID чата группы'),
        ),
        migrations.AddField(
            model_name='telegramactivitylog',
            name='group_message_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Telegram message_ids sent to the group (for deletion)', verbose_name='ID сообщений в группе'),
        ),
        migrations.AlterField(
            model_name='telegramactivitylog',
            name='group_notification_status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('error', 'Ошибка'), ('not_applicable', 'Не применимо'), ('cancelled', 'Отменено')], default='not_applicable', max_length=20, verbose_name='Статус уведомления группы'),
        ),
    ]
