# Generated by Django 5.2.6 on 2026-01-15 06:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_initial_tariff_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('effective_from', models.DateField(help_text='Дата начала действия тарифа', verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, help_text='Дата окончания действия (NULL = действует сейчас)', null=True, verbose_name='Действует до')),
                ('notes', models.TextField(blank=True, default='', help_text='Причина создания/изменения тарифа', verbose_name='Примечания')),
                ('company', models.ForeignKey(blank=True, help_text='NULL = общий тариф, указана компания = специальный тариф', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='accounts.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('container_size', models.CharField(choices=[('20ft', '20 футов'), ('40ft', '40 футов')], max_length=10, verbose_name='Размер контейнера')),
                ('container_status', models.CharField(choices=[('laden', 'Груженый'), ('empty', 'Порожний')], max_length=10, verbose_name='Статус контейнера')),
                ('daily_rate_usd', models.DecimalField(decimal_places=2, help_text='Дневная ставка хранения в долларах США', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ставка USD/день')),
                ('daily_rate_uzs', models.DecimalField(decimal_places=2, help_text='Дневная ставка хранения в сумах', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ставка UZS/день')),
                ('free_days', models.PositiveIntegerField(default=0, help_text='Количество бесплатных дней хранения', verbose_name='Бесплатные дни')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='billing.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Ставка тарифа',
                'verbose_name_plural': 'Ставки тарифов',
                'ordering': ['tariff', 'container_size', 'container_status'],
            },
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['company', 'effective_from', 'effective_to'], name='tariff_company_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['effective_from'], name='tariff_eff_from_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['effective_to'], name='tariff_eff_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('company', 'effective_from'), name='unique_tariff_per_company_date'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='tariff_effective_to_after_from'),
        ),
        migrations.AddConstraint(
            model_name='tariffrate',
            constraint=models.UniqueConstraint(fields=('tariff', 'container_size', 'container_status'), name='unique_rate_per_tariff_size_status'),
        ),
    ]
