# Generated by Django 5.2.6 on 2026-01-19 16:30
"""
Data migration to fix incorrect TariffRate values.

Fixes:
- container_size: "20" -> "20ft", "40" -> "40ft"
- container_status: "LADEN" -> "laden", "EMPTY" -> "empty"

These values must match the ContainerSize and ContainerBillingStatus TextChoices
defined in apps/billing/models.py for the storage cost calculation to work.
"""

from django.db import migrations


def fix_tariff_rate_values(apps, schema_editor):
    """Fix incorrect container_size and container_status values."""
    TariffRate = apps.get_model("billing", "TariffRate")

    # Fix container_size values
    TariffRate.objects.filter(container_size="20").update(container_size="20ft")
    TariffRate.objects.filter(container_size="40").update(container_size="40ft")

    # Fix container_status values (uppercase -> lowercase)
    TariffRate.objects.filter(container_status="LADEN").update(container_status="laden")
    TariffRate.objects.filter(container_status="EMPTY").update(container_status="empty")


def reverse_fix(apps, schema_editor):
    """Reverse the fix (for rollback)."""
    TariffRate = apps.get_model("billing", "TariffRate")

    # Reverse container_size values
    TariffRate.objects.filter(container_size="20ft").update(container_size="20")
    TariffRate.objects.filter(container_size="40ft").update(container_size="40")

    # Reverse container_status values
    TariffRate.objects.filter(container_status="laden").update(container_status="LADEN")
    TariffRate.objects.filter(container_status="empty").update(container_status="EMPTY")


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial_tariff_models"),
    ]

    operations = [
        migrations.RunPython(fix_tariff_rate_values, reverse_fix),
    ]
