# Generated by Django 5.2.6 on 2026-01-19 17:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_billing_method'),
        ('billing', '0002_fix_tariff_rate_values'),
        ('terminal_operations', '0022_convert_workorder_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('billing_method', models.CharField(choices=[('split', 'Раздельный расчёт'), ('exit_month', 'По месяцу выхода')], help_text='Snapshot of billing method used at generation time', max_length=20, verbose_name='Метод расчёта')),
                ('total_containers', models.PositiveIntegerField(default=0, verbose_name='Всего контейнеров')),
                ('total_billable_days', models.PositiveIntegerField(default=0, verbose_name='Оплачиваемых дней')),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого USD')),
                ('total_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Итого UZS')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.company', verbose_name='Компания')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL, verbose_name='Сформировано пользователем')),
            ],
            options={
                'verbose_name': 'Ежемесячная выписка',
                'verbose_name_plural': 'Ежемесячные выписки',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='StatementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('container_number', models.CharField(max_length=20, verbose_name='Номер контейнера')),
                ('container_size', models.CharField(choices=[('20ft', '20 футов'), ('40ft', '40 футов')], max_length=10, verbose_name='Размер контейнера')),
                ('container_status', models.CharField(choices=[('laden', 'Груженый'), ('empty', 'Порожний')], max_length=10, verbose_name='Статус контейнера')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('is_still_on_terminal', models.BooleanField(default=False, verbose_name='На терминале')),
                ('total_days', models.PositiveIntegerField(verbose_name='Всего дней')),
                ('free_days', models.PositiveIntegerField(verbose_name='Льготных дней')),
                ('billable_days', models.PositiveIntegerField(verbose_name='Оплачиваемых дней')),
                ('daily_rate_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка USD/день')),
                ('daily_rate_uzs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ставка UZS/день')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма USD')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма UZS')),
                ('container_entry', models.ForeignKey(help_text='Reference to original entry (may be null if deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_line_items', to='terminal_operations.containerentry', verbose_name='Запись контейнера')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.monthlystatement', verbose_name='Выписка')),
            ],
            options={
                'verbose_name': 'Позиция выписки',
                'verbose_name_plural': 'Позиции выписки',
                'ordering': ['container_number'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlystatement',
            index=models.Index(fields=['company', 'year', 'month'], name='statement_company_period_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlystatement',
            index=models.Index(fields=['year', 'month'], name='statement_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlystatement',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_statement_per_company_month'),
        ),
        migrations.AddIndex(
            model_name='statementlineitem',
            index=models.Index(fields=['statement', 'container_number'], name='lineitem_stmt_container_idx'),
        ),
    ]
