# Generated by Django 5.2.6 on 2026-01-20 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_monthlystatement_statementlineitem'),
        ('terminal_operations', '0022_convert_workorder_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма USD')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма UZS')),
                ('charge_date', models.DateField(verbose_name='Дата начисления')),
                ('container_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='terminal_operations.containerentry', verbose_name='Запись контейнера')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charges', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Дополнительное начисление',
                'verbose_name_plural': 'Дополнительные начисления',
                'ordering': ['-charge_date', '-created_at'],
                'indexes': [models.Index(fields=['container_entry', 'charge_date'], name='charge_entry_date_idx'), models.Index(fields=['charge_date'], name='charge_date_idx')],
            },
        ),
    ]
