# Generated by Django 5.2.6 on 2026-01-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_expense_type_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlystatement',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='paid_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_paid_statements', to=settings.AUTH_USER_MODEL, verbose_name='Отметил оплату'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=10, verbose_name='Статус оплаты'),
        ),
    ]
