# Generated by Django 5.2.6 on 2026-01-27 06:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_payment_status_to_lifecycle(apps, schema_editor):
    """Migrate existing payment_status to new status field and copy totals."""
    MonthlyStatement = apps.get_model("billing", "MonthlyStatement")
    for stmt in MonthlyStatement.objects.all():
        # Map old payment_status to new status
        if stmt.payment_status == "paid":
            stmt.status = "paid"
        else:
            stmt.status = "draft"
        # Copy totals to storage-specific fields (no services existed before)
        stmt.total_storage_usd = stmt.total_usd
        stmt.total_storage_uzs = stmt.total_uzs
        stmt.save(update_fields=["status", "total_storage_usd", "total_storage_uzs"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_billing_method'),
        ('billing', '0006_add_payment_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create new model
        migrations.CreateModel(
            name='StatementServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('container_number', models.CharField(max_length=20, verbose_name='Номер контейнера')),
                ('description', models.CharField(max_length=255, verbose_name='Описание услуги')),
                ('charge_date', models.DateField(verbose_name='Дата начисления')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма USD')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма UZS')),
            ],
            options={
                'verbose_name': 'Позиция услуг',
                'verbose_name_plural': 'Позиции услуг',
                'ordering': ['charge_date', 'container_number'],
            },
        ),
        # 2. Add new fields to MonthlyStatement (before removing payment_status)
        migrations.AddField(
            model_name='monthlystatement',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_statements', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Assigned on finalization, format: MTT-YYYY-NNNN or MTT-CR-YYYY-NNNN', max_length=30, null=True, unique=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='original_statement',
            field=models.ForeignKey(blank=True, help_text='For credit notes: references the original statement being corrected', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.monthlystatement', verbose_name='Исходный документ'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='pending_containers_data',
            field=models.JSONField(blank=True, help_text='JSON snapshot of containers still on terminal at generation time', null=True, verbose_name='Контейнеры на терминале'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='statement_type',
            field=models.CharField(choices=[('invoice', 'Счёт'), ('credit_note', 'Корректировка')], default='invoice', max_length=15, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=15, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='total_services_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Услуги USD'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='total_services_uzs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Услуги UZS'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='total_storage_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Хранение USD'),
        ),
        migrations.AddField(
            model_name='monthlystatement',
            name='total_storage_uzs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Хранение UZS'),
        ),
        # 3. Data migration: copy payment_status → status, totals → storage totals
        migrations.RunPython(
            migrate_payment_status_to_lifecycle,
            migrations.RunPython.noop,
        ),
        # 4. Now safe to remove old field and constraint
        migrations.RemoveConstraint(
            model_name='monthlystatement',
            name='unique_statement_per_company_month',
        ),
        migrations.RemoveField(
            model_name='monthlystatement',
            name='payment_status',
        ),
        # 5. Add new indexes and constraints
        migrations.AddIndex(
            model_name='monthlystatement',
            index=models.Index(fields=['status'], name='statement_status_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlystatement',
            index=models.Index(fields=['invoice_number'], name='statement_invoice_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlystatement',
            constraint=models.UniqueConstraint(condition=models.Q(('statement_type', 'invoice')), fields=('company', 'year', 'month'), name='unique_invoice_per_company_month'),
        ),
        # 6. StatementServiceItem FKs and indexes
        migrations.AddField(
            model_name='statementserviceitem',
            name='additional_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_service_items', to='billing.additionalcharge', verbose_name='Начисление'),
        ),
        migrations.AddField(
            model_name='statementserviceitem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='billing.monthlystatement', verbose_name='Выписка'),
        ),
        migrations.AddIndex(
            model_name='statementserviceitem',
            index=models.Index(fields=['statement', 'charge_date'], name='svcitem_stmt_date_idx'),
        ),
    ]
