# Generated by Django 5.2.6 on 2026-02-04 06:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_billing_method'),
        ('billing', '0007_statement_lifecycle_and_service_items'),
        ('terminal_operations', '0026_add_dxf_fields_to_container_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('invoice_number', models.CharField(blank=True, help_text='Assigned on finalization, format: OD-YYYY-NNNN', max_length=30, null=True, unique=True, verbose_name='Номер счёта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=15, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', help_text='Причина выставления разового счёта', verbose_name='Примечания')),
                ('total_containers', models.PositiveIntegerField(default=0, verbose_name='Всего контейнеров')),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого USD')),
                ('total_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Итого UZS')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_demand_invoices', to='accounts.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_on_demand_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_on_demand_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('paid_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_paid_on_demand_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Отметил оплату')),
            ],
            options={
                'verbose_name': 'Разовый счёт',
                'verbose_name_plural': 'Разовые счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnDemandInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('container_number', models.CharField(max_length=20, verbose_name='Номер контейнера')),
                ('container_size', models.CharField(choices=[('20ft', '20 футов'), ('40ft', '40 футов')], max_length=10, verbose_name='Размер контейнера')),
                ('container_status', models.CharField(choices=[('laden', 'Груженый'), ('empty', 'Порожний')], max_length=10, verbose_name='Статус контейнера')),
                ('entry_date', models.DateField(verbose_name='Дата въезда')),
                ('exit_date', models.DateField(verbose_name='Дата выезда')),
                ('total_days', models.PositiveIntegerField(verbose_name='Всего дней')),
                ('free_days', models.PositiveIntegerField(verbose_name='Льготных дней')),
                ('billable_days', models.PositiveIntegerField(verbose_name='Оплачиваемых дней')),
                ('daily_rate_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка USD/день')),
                ('daily_rate_uzs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ставка UZS/день')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма USD')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма UZS')),
                ('container_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_demand_items', to='terminal_operations.containerentry', verbose_name='Запись контейнера')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.ondemandinvoice', verbose_name='Разовый счёт')),
            ],
            options={
                'verbose_name': 'Позиция разового счёта',
                'verbose_name_plural': 'Позиции разового счёта',
                'ordering': ['container_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ondemandinvoice',
            index=models.Index(fields=['company', 'status'], name='od_invoice_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ondemandinvoice',
            index=models.Index(fields=['status'], name='od_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ondemandinvoice',
            index=models.Index(fields=['invoice_number'], name='od_invoice_number_idx'),
        ),
        migrations.AddIndex(
            model_name='ondemandinvoiceitem',
            index=models.Index(fields=['invoice', 'container_number'], name='od_item_invoice_container_idx'),
        ),
        migrations.AddIndex(
            model_name='ondemandinvoiceitem',
            index=models.Index(fields=['container_entry'], name='od_item_entry_idx'),
        ),
    ]
