# Generated by Django 5.2.6 on 2026-02-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_on_demand_invoice_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandInvoiceServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('container_number', models.CharField(max_length=20, verbose_name='Номер контейнера')),
                ('description', models.CharField(max_length=255, verbose_name='Описание услуги')),
                ('charge_date', models.DateField(verbose_name='Дата начисления')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма USD')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма UZS')),
                ('additional_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_demand_service_items', to='billing.additionalcharge', verbose_name='Доп. начисление')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='billing.ondemandinvoice', verbose_name='Разовый счёт')),
            ],
            options={
                'verbose_name': 'Услуга разового счёта',
                'verbose_name_plural': 'Услуги разового счёта',
                'ordering': ['charge_date', 'container_number'],
                'indexes': [models.Index(fields=['invoice', 'charge_date'], name='od_svc_invoice_date_idx')],
            },
        ),
    ]
