# Generated by Django 5.2.6 on 2026-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_on_demand_service_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondemandinvoiceitem',
            name='exit_date',
            field=models.DateField(blank=True, help_text='NULL = контейнер на терминале при выставлении счёта', null=True, verbose_name='Дата выезда'),
        ),
    ]
