# Generated by Django 5.2.6 on 2026-02-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_nullable_exit_date_for_active_invoicing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ondemandinvoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Обязательно при отмене утверждённого счёта', verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='ondemandinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='ondemandinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_on_demand_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='ondemandinvoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Фактическая дата оплаты (может отличаться от даты отметки)', null=True, verbose_name='Дата платежа'),
        ),
        migrations.AddField(
            model_name='ondemandinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Номер банковской транзакции, чека и т.д.', max_length=100, verbose_name='Референс платежа'),
        ),
    ]
