# Generated by Django 5.2.6 on 2026-02-06 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_cancellation_and_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('company_name', models.CharField(blank=True, default='', help_text='Например: ООО "MULTIMODAL TRANS TERMINAL"', max_length=255, verbose_name='Наименование организации')),
                ('legal_address', models.TextField(blank=True, default='', verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('bank_name', models.CharField(blank=True, default='', help_text='Например: АКБ "Xamkor Bank", Яккасарой ф-л', max_length=255, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, default='', max_length=50, verbose_name='Расчётный счёт')),
                ('mfo', models.CharField(blank=True, default='', max_length=20, verbose_name='МФО')),
                ('inn', models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН')),
                ('vat_registration_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Код плательщика НДС')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Текущая ставка НДС в процентах', max_digits=5, verbose_name='Ставка НДС (%)')),
                ('director_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Руководитель (ФИО)')),
                ('director_title', models.CharField(blank=True, default='Руководитель', max_length=100, verbose_name='Должность руководителя')),
                ('accountant_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Гл. бухгалтер (ФИО)')),
                ('basis_document', models.CharField(blank=True, default='Устава', help_text='На основании чего действует (Устава, Доверенности и т.д.)', max_length=255, verbose_name='Основание')),
                ('default_usd_uzs_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Курс ЦБ по умолчанию. Может быть переопределён при формировании документа.', max_digits=12, verbose_name='Курс USD → UZS')),
            ],
            options={
                'verbose_name': 'Настройки терминала',
                'verbose_name_plural': 'Настройки терминала',
            },
        ),
    ]
