# Generated by Django 5.2.6 on 2026-02-06 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_populate_terminal_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlystatement',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Курс ЦБ на дату документа. Замораживается при утверждении.', max_digits=12, null=True, verbose_name='Курс USD → UZS'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Курс ЦБ')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='unique_rate_per_currency_date')],
            },
        ),
    ]
