# Generated by Django 5.2.6 on 2026-02-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_company_contract_fields'),
        ('billing', '0014_add_exchange_rate_model_and_statement_field'),
        ('terminal_operations', '0027_audit_protect_financial_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='container_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additional_charges', to='terminal_operations.containerentry', verbose_name='Запись контейнера'),
        ),
        migrations.AlterField(
            model_name='monthlystatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='ondemandinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='on_demand_invoices', to='accounts.company', verbose_name='Компания'),
        ),
    ]
