# Generated by Django 5.2.6 on 2025-09-22 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container_number",
                    models.CharField(
                        help_text="Container number in format: 4 letters + 7 digits",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format: 4 letters + 7 digits (e.g., MSKU1234567)",
                                regex="^[A-Z]{4}[0-9]{7}$",
                            )
                        ],
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("20", "20ft"),
                            ("40", "40ft"),
                            ("40HC", "40ft High Cube"),
                            ("45", "45ft"),
                        ],
                        default="20",
                        max_length=4,
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("GP", "General Purpose"),
                            ("HC", "High Cube"),
                            ("RF", "Refrigerated"),
                            ("OT", "Open Top"),
                            ("FR", "Flat Rack"),
                        ],
                        default="GP",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
                "ordering": ["container_number"],
            },
        ),
    ]
