# Generated by Django 5.2.6 on 2025-10-03 07:19

from django.db import migrations, models


def convert_to_iso_type(apps, schema_editor):
    """Convert old size + container_type to ISO 6346 codes"""
    Container = apps.get_model("containers", "Container")

    # Mapping: (size, container_type) -> iso_type
    mapping = {
        ("20", "GP"): "22G1",
        ("40", "GP"): "42G1",
        ("40HC", "GP"): "45G1",
        ("40HC", "HC"): "45G1",
        ("45", "GP"): "L5G1",
        ("45", "HC"): "L5G1",
        ("20", "RF"): "22R1",
        ("40", "RF"): "42R1",
        ("40HC", "RF"): "45R1",
        ("45", "RF"): "L5R1",
        ("20", "OT"): "22U1",
        ("40", "OT"): "42U1",
        ("40HC", "OT"): "45U1",
        ("20", "FR"): "22P1",
        ("40", "FR"): "42P1",
        ("40HC", "FR"): "45P1",
    }

    for container in Container.objects.all():
        key = (container.size, container.container_type)
        iso_type = mapping.get(key, "22G1")  # Default to 22G1 if not found
        container.iso_type = iso_type
        container.save(update_fields=["iso_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0001_initial"),
    ]

    operations = [
        # Add iso_type field
        migrations.AddField(
            model_name="container",
            name="iso_type",
            field=models.CharField(
                choices=[
                    ("22G1", "22G1"),
                    ("42G1", "42G1"),
                    ("45G1", "45G1"),
                    ("L5G1", "L5G1"),
                    ("22R1", "22R1"),
                    ("42R1", "42R1"),
                    ("45R1", "45R1"),
                    ("L5R1", "L5R1"),
                    ("22U1", "22U1"),
                    ("42U1", "42U1"),
                    ("45U1", "45U1"),
                    ("22P1", "22P1"),
                    ("42P1", "42P1"),
                    ("45P1", "45P1"),
                    ("22T1", "22T1"),
                    ("42T1", "42T1"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        # Convert existing data
        migrations.RunPython(
            convert_to_iso_type, reverse_code=migrations.RunPython.noop
        ),
        # Make iso_type required
        migrations.AlterField(
            model_name="container",
            name="iso_type",
            field=models.CharField(
                choices=[
                    ("22G1", "22G1"),
                    ("42G1", "42G1"),
                    ("45G1", "45G1"),
                    ("L5G1", "L5G1"),
                    ("22R1", "22R1"),
                    ("42R1", "42R1"),
                    ("45R1", "45R1"),
                    ("L5R1", "L5R1"),
                    ("22U1", "22U1"),
                    ("42U1", "42U1"),
                    ("45U1", "45U1"),
                    ("22P1", "22P1"),
                    ("42P1", "42P1"),
                    ("45P1", "45P1"),
                    ("22T1", "22T1"),
                    ("42T1", "42T1"),
                ],
                max_length=4,
            ),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="container",
            name="size",
        ),
        migrations.RemoveField(
            model_name="container",
            name="container_type",
        ),
    ]
