# Generated by Django 5.2.6 on 2025-10-03 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0002_convert_to_iso_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "ordering": ["container_number"],
                "verbose_name": "Контейнер",
                "verbose_name_plural": "Контейнеры",
            },
        ),
        migrations.AlterField(
            model_name="container",
            name="container_number",
            field=models.CharField(
                help_text="Номер контейнера в формате: 4 буквы + 7 цифр",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Формат: 4 буквы + 7 цифр (например, MSKU1234567)",
                        regex="^[A-Z]{4}[0-9]{7}$",
                    )
                ],
            ),
        ),
    ]
