# Generated by Django 5.2.6 on 2025-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0003_alter_container_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="iso_type",
            field=models.CharField(
                choices=[
                    ("22G1", "22G1"),
                    ("22K2", "22K2"),
                    ("25G1", "25G1"),
                    ("42G1", "42G1"),
                    ("45G1", "45G1"),
                    ("L5G1", "L5G1"),
                    ("22R1", "22R1"),
                    ("42R1", "42R1"),
                    ("45R1", "45R1"),
                    ("L5R1", "L5R1"),
                    ("22U1", "22U1"),
                    ("42U1", "42U1"),
                    ("45U1", "45U1"),
                    ("22P1", "22P1"),
                    ("42P1", "42P1"),
                    ("45P1", "45P1"),
                    ("22T1", "22T1"),
                    ("42T1", "42T1"),
                ],
                max_length=4,
            ),
        ),
    ]
