# Generated by Django 5.2.6 on 2026-01-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_alter_container_iso_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='container',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
