# Generated by Django 5.2.6 on 2025-12-05 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250922_0933'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bot_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к боту'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gate_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к воротам'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], default='ru', max_length=5, verbose_name='Язык уведомлений'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+998901234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'API User'), ('manager', 'Telegram Manager'), ('customer', 'Customer')], default='admin', help_text='User type determines access method: admin (API with username) or manager (Telegram with phone)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='accounts_cu_user_ty_97b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='accounts_cu_phone_n_908ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telegram_user_id'], name='accounts_cu_telegra_2bafc7_idx'),
        ),
    ]
