# Generated by Django 5.2.6 on 2026-01-06 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bot_access',
            field=models.BooleanField(default=False, verbose_name='[LEGACY] Доступ к боту'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gate_access',
            field=models.BooleanField(default=False, verbose_name='[LEGACY] Доступ к воротам'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], default='ru', max_length=5, verbose_name='[LEGACY] Язык уведомлений'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='[LEGACY] Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='[LEGACY] Telegram User ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='[LEGACY] Telegram Username'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, auto-generated from name', max_length=255, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_co_name_a6c199_idx'), models.Index(fields=['slug'], name='accounts_co_slug_92d758_idx'), models.Index(fields=['is_active'], name='accounts_co_is_acti_4abc2f_idx')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='LEGACY - use profile.company instead', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.company', verbose_name='[LEGACY] Компания'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+998901234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram Username')),
                ('bot_access', models.BooleanField(default=False, verbose_name='Доступ к боту')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], default='ru', max_length=5, verbose_name='Язык уведомлений')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.company', verbose_name='Компания')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
                'indexes': [models.Index(fields=['phone_number'], name='accounts_cu_phone_n_f3811d_idx'), models.Index(fields=['telegram_user_id'], name='accounts_cu_telegra_78b2d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+998901234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram Username')),
                ('bot_access', models.BooleanField(default=False, verbose_name='Доступ к боту')),
                ('gate_access', models.BooleanField(default=False, verbose_name='Доступ к воротам')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha")], default='ru', max_length=5, verbose_name='Язык уведомлений')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='accounts.company', verbose_name='Компания')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль менеджера',
                'verbose_name_plural': 'Профили менеджеров',
                'indexes': [models.Index(fields=['phone_number'], name='accounts_ma_phone_n_88da18_idx'), models.Index(fields=['telegram_user_id'], name='accounts_ma_telegra_7588c8_idx')],
            },
        ),
    ]
