# Generated by Django 5.2.6 on 2026-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_bot_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notifications_enabled',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления в Telegram при создании записей контейнеров', verbose_name='Уведомления включены'),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram_group_id',
            field=models.CharField(blank=True, help_text='ID группы Telegram для уведомлений (например: -1001234567890)', max_length=50, null=True, verbose_name='Telegram Group ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='telegram_group_name',
            field=models.CharField(blank=True, default='', help_text='Название группы для отображения', max_length=100, verbose_name='Название группы'),
        ),
    ]
