# Generated by Django 5.2.6 on 2026-01-18 09:21

from django.db import migrations


def populate_manager_profiles(apps, schema_editor):
    """
    Migrate legacy CustomUser fields to ManagerProfile for user_type='manager'.
    Creates ManagerProfile instances with data from legacy fields.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    ManagerProfile = apps.get_model('accounts', 'ManagerProfile')

    # Get all manager users who don't have profiles yet
    managers = CustomUser.objects.filter(user_type='manager')

    created_count = 0
    skipped_count = 0

    for manager in managers:
        # Skip if profile already exists
        if ManagerProfile.objects.filter(user=manager).exists():
            skipped_count += 1
            continue

        # Skip if no phone number (required field for profile)
        if not manager.phone_number:
            print(f"WARNING: Manager {manager.id} has no phone_number, skipping profile creation")
            skipped_count += 1
            continue

        # Create profile from legacy fields
        ManagerProfile.objects.create(
            user=manager,
            phone_number=manager.phone_number,
            telegram_user_id=manager.telegram_user_id,
            telegram_username=manager.telegram_username or '',
            bot_access=manager.bot_access,
            gate_access=manager.gate_access,
            language=manager.language or 'ru',
            company=manager.company,
        )
        created_count += 1

    print(f"Migration complete: Created {created_count} manager profiles, skipped {skipped_count}")


def reverse_populate_manager_profiles(apps, schema_editor):
    """
    Reverse migration: Copy data from ManagerProfile back to CustomUser legacy fields.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    ManagerProfile = apps.get_model('accounts', 'ManagerProfile')

    profiles = ManagerProfile.objects.select_related('user').all()

    for profile in profiles:
        user = profile.user
        user.phone_number = profile.phone_number
        user.telegram_user_id = profile.telegram_user_id
        user.telegram_username = profile.telegram_username
        user.bot_access = profile.bot_access
        user.gate_access = profile.gate_access
        user.language = profile.language
        user.company = profile.company
        user.save()

    print(f"Reverse migration complete: Restored {profiles.count()} manager legacy fields")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_initial_tariff_models'),
    ]

    operations = [
        migrations.RunPython(populate_manager_profiles, reverse_populate_manager_profiles),
    ]
