# Generated by Django 5.2.6 on 2026-01-18 09:21

from django.db import migrations


def populate_customer_profiles(apps, schema_editor):
    """
    Migrate legacy CustomUser fields to CustomerProfile for user_type='customer'.
    Creates CustomerProfile instances with data from legacy fields.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')

    # Get all customer users who don't have profiles yet
    customers = CustomUser.objects.filter(user_type='customer')

    created_count = 0
    skipped_count = 0

    for customer in customers:
        # Skip if profile already exists
        if CustomerProfile.objects.filter(user=customer).exists():
            skipped_count += 1
            continue

        # Skip if no phone number (required field for profile)
        if not customer.phone_number:
            print(f"WARNING: Customer {customer.id} has no phone_number, skipping profile creation")
            skipped_count += 1
            continue

        # Skip if no company (required field for customer profile)
        if not customer.company:
            print(f"WARNING: Customer {customer.id} has no company, skipping profile creation")
            skipped_count += 1
            continue

        # Create profile from legacy fields
        CustomerProfile.objects.create(
            user=customer,
            phone_number=customer.phone_number,
            telegram_user_id=customer.telegram_user_id,
            telegram_username=customer.telegram_username or '',
            bot_access=customer.bot_access,
            language=customer.language or 'ru',
            company=customer.company,
        )
        created_count += 1

    print(f"Migration complete: Created {created_count} customer profiles, skipped {skipped_count}")


def reverse_populate_customer_profiles(apps, schema_editor):
    """
    Reverse migration: Copy data from CustomerProfile back to CustomUser legacy fields.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')

    profiles = CustomerProfile.objects.select_related('user').all()

    for profile in profiles:
        user = profile.user
        user.phone_number = profile.phone_number
        user.telegram_user_id = profile.telegram_user_id
        user.telegram_username = profile.telegram_username
        user.bot_access = profile.bot_access
        user.language = profile.language
        user.company = profile.company
        user.save()

    print(f"Reverse migration complete: Restored {profiles.count()} customer legacy fields")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_populate_manager_profiles'),
    ]

    operations = [
        migrations.RunPython(populate_customer_profiles, reverse_populate_customer_profiles),
    ]
