# Generated by Django 5.2.6 on 2026-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_populate_customer_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_method',
            field=models.CharField(choices=[('split', 'Раздельный расчёт'), ('exit_month', 'По месяцу выхода')], default='split', help_text='Метод расчёта для ежемесячных выписок', max_length=20, verbose_name='Метод расчёта'),
        ),
    ]
