# Generated by Django 5.2.6 on 2026-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_billing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='mfo',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='МФО'),
        ),
    ]
