# Generated by Django 5.2.6 on 2026-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_company_legal_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_expires',
            field=models.DateField(blank=True, help_text='Оставьте пустым для бессрочного договора', null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_file',
            field=models.FileField(blank=True, help_text='PDF или скан договора', upload_to='contracts/%Y/', verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер договора'),
        ),
    ]
