# Generated by Django 5.2.6 on 2025-09-22 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("containers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("EMPTY", "Empty"), ("LADEN", "Laden")], max_length=10
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("TRUCK", "Truck"), ("WAGON", "Railway Wagon")],
                        max_length=10,
                    ),
                ),
                (
                    "transport_id",
                    models.CharField(
                        blank=True,
                        help_text="Truck license plate or wagon number",
                        max_length=50,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="containers.container",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Entry",
                "verbose_name_plural": "Container Entries",
                "ordering": ["-entry_time"],
            },
        ),
    ]
