# Generated by Django 5.2.6 on 2025-09-22 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerEntryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Supported formats: JPG, PNG, WebP",
                        upload_to="container_entries/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front View"),
                            ("BACK", "Back View"),
                            ("LEFT", "Left Side"),
                            ("RIGHT", "Right Side"),
                            ("DAMAGE", "Damage Documentation"),
                            ("SEAL", "Seal/Lock Documentation"),
                            ("PLATE", "License Plate"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of what this image shows",
                        max_length=200,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="terminal_operations.containerentry",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Entry Image",
                "verbose_name_plural": "Container Entry Images",
                "ordering": ["image_type", "created_at"],
            },
        ),
    ]
