# Generated by Django 5.2.6 on 2025-09-22 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0002_containerentryimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containerentryimage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Container Entry Image",
                "verbose_name_plural": "Container Entry Images",
            },
        ),
        migrations.RemoveField(
            model_name="containerentryimage",
            name="image_type",
        ),
    ]
