# Generated by Django 5.2.6 on 2025-10-02 07:16

import apps.core.validators
import apps.terminal_operations.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0001_initial"),
        ("terminal_operations", "0003_alter_containerentryimage_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerentryimage",
            name="image",
            field=models.ImageField(
                help_text="Supported formats: JPG, PNG, WebP (max 10MB)",
                upload_to="container_entries/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.core.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="containerentry",
            index=models.Index(fields=["-entry_time"], name="entry_time_idx"),
        ),
        migrations.AddIndex(
            model_name="containerentry",
            index=models.Index(
                fields=["container", "-entry_time"], name="container_entry_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="containerentry",
            index=models.Index(
                fields=["status", "-entry_time"], name="status_entry_time_idx"
            ),
        ),
    ]
