# Generated by Django 5.2.6 on 2025-10-03 06:24

import apps.core.validators
import apps.terminal_operations.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0004_alter_containerentryimage_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containerentry",
            options={
                "ordering": ["-entry_time"],
                "verbose_name": "Въезд контейнера",
                "verbose_name_plural": "Въезды контейнеров",
            },
        ),
        migrations.AlterModelOptions(
            name="containerentryimage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Изображение въезда контейнера",
                "verbose_name_plural": "Изображения въездов контейнеров",
            },
        ),
        migrations.RenameField(
            model_name="containerentry",
            old_name="transport_id",
            new_name="transport_number",
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="status",
            field=models.CharField(
                choices=[("EMPTY", "Порожний"), ("LADEN", "Гружёный")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="transport_type",
            field=models.CharField(
                choices=[("TRUCK", "Грузовик"), ("WAGON", "Вагон")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="containerentryimage",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Описание изображения (необязательно)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="containerentryimage",
            name="image",
            field=models.ImageField(
                help_text="Поддерживаемые форматы: JPG, PNG, WebP (макс. 10MB)",
                upload_to="container_entries/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    apps.core.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="containerentryimage",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="Пользователь, загрузивший изображение",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
