# Generated by Django 5.2.6 on 2025-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0005_rename_transport_id_to_transport_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerentry",
            name="transport_number",
            field=models.CharField(
                blank=True, help_text="Номер грузовика или вагона", max_length=50
            ),
        ),
    ]
