# Generated by Django 5.2.6 on 2025-10-15 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0006_alter_containerentry_transport_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContainerEntryImage",
        ),
    ]
