# Generated by Django 5.2.6 on 2025-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0007_remove_container_entry_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerentry",
            name="cargo_name",
            field=models.CharField(
                blank=True, help_text="Наименование груза", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="client_name",
            field=models.CharField(
                blank=True, help_text="Наименование клиента", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="container_owner",
            field=models.CharField(
                blank=True,
                help_text="Собственник контейнера",
                max_length=250,
                null=True,
            ),
        ),
    ]
