# Generated by Django 5.2.6 on 2025-10-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("containers", "0003_alter_container_options_and_more"),
        (
            "terminal_operations",
            "0008_containerentry_cargo_name_containerentry_client_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCraneOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_date",
                    models.DateTimeField(
                        help_text="Дата и время проведения крановой операции"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание выполненной крановой операции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная крановая операция",
                "verbose_name_plural": "Дополнительные крановые операции",
                "ordering": ["operation_date"],
            },
        ),
        migrations.AddField(
            model_name="containerentry",
            name="cargo_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вес груза в тоннах",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="destination_station",
            field=models.CharField(
                blank=True, help_text="Станция назначения", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="dwell_time_days",
            field=models.IntegerField(
                blank=True,
                help_text="Количество дней на хранение (может быть рассчитано автоматически)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="exit_date",
            field=models.DateTimeField(
                blank=True, help_text="Дата вывоза контейнера с терминала", null=True
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="exit_train_number",
            field=models.CharField(
                blank=True,
                help_text="Номер поезда при вывозе",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="exit_transport_number",
            field=models.CharField(
                blank=True,
                help_text="Номер машины/вагона при вывозе",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="exit_transport_type",
            field=models.CharField(
                blank=True,
                choices=[("TRUCK", "Грузовик"), ("WAGON", "Вагон"), ("TRAIN", "Поезд")],
                help_text="Тип транспорта при вывозе",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Местоположение на терминале",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="note",
            field=models.TextField(blank=True, help_text="Примечание", null=True),
        ),
        migrations.AddIndex(
            model_name="containerentry",
            index=models.Index(fields=["-exit_date"], name="exit_date_idx"),
        ),
        migrations.AddIndex(
            model_name="containerentry",
            index=models.Index(
                fields=["exit_transport_type", "-exit_date"], name="exit_type_date_idx"
            ),
        ),
        migrations.AddField(
            model_name="additionalcraneoperation",
            name="container_entry",
            field=models.ForeignKey(
                help_text="Запись о ввозе контейнера, к которой относится операция",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crane_operations",
                to="terminal_operations.containerentry",
            ),
        ),
        migrations.AddIndex(
            model_name="additionalcraneoperation",
            index=models.Index(
                fields=["container_entry", "operation_date"],
                name="crane_op_entry_date_idx",
            ),
        ),
    ]
