# Generated by Django 5.2.6 on 2025-10-17 05:22

from django.db import migrations, models


def convert_null_to_empty_string(apps, schema_editor):
    """Convert NULL values to empty strings for CharField and TextField"""
    ContainerEntry = apps.get_model("terminal_operations", "ContainerEntry")

    # Fields to update
    text_fields = [
        "client_name",
        "container_owner",
        "cargo_name",
        "exit_train_number",
        "exit_transport_number",
        "destination_station",
        "location",
        "note",
    ]

    # Update each field
    for field_name in text_fields:
        filter_kwargs = {f"{field_name}__isnull": True}
        update_kwargs = {field_name: ""}
        ContainerEntry.objects.filter(**filter_kwargs).update(**update_kwargs)


def reverse_conversion(apps, schema_editor):
    """Reverse operation: empty strings back to NULL (for rollback)"""
    ContainerEntry = apps.get_model("terminal_operations", "ContainerEntry")

    # Fields to update
    text_fields = [
        "client_name",
        "container_owner",
        "cargo_name",
        "exit_train_number",
        "exit_transport_number",
        "destination_station",
        "location",
        "note",
    ]

    # Update each field - convert empty strings back to NULL
    for field_name in text_fields:
        filter_kwargs = {field_name: ""}
        update_kwargs = {field_name: None}
        ContainerEntry.objects.filter(**filter_kwargs).update(**update_kwargs)


class Migration(migrations.Migration):
    dependencies = [
        (
            "terminal_operations",
            "0009_additionalcraneoperation_containerentry_cargo_weight_and_more",
        ),
    ]

    operations = [
        # First, convert existing NULL values to empty strings
        migrations.RunPython(convert_null_to_empty_string, reverse_conversion),
        # Then, alter the fields to remove null=True
        migrations.AlterField(
            model_name="containerentry",
            name="cargo_name",
            field=models.CharField(
                blank=True, default="", help_text="Наименование груза", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="client_name",
            field=models.CharField(
                blank=True, default="", help_text="Наименование клиента", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="container_owner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Собственник контейнера",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="destination_station",
            field=models.CharField(
                blank=True, default="", help_text="Станция назначения", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="exit_train_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Номер поезда при вывозе",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="exit_transport_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Номер машины/вагона при вывозе",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Местоположение на терминале",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="note",
            field=models.TextField(blank=True, default="", help_text="Примечание"),
        ),
    ]
