# Generated by Django 5.2.6 on 2025-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminal_operations", "0010_alter_containerentry_cargo_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerentry",
            name="additional_crane_operation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата и время дополнительной крановой операции",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="containerentry",
            name="entry_train_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Номер поезда при ввозе",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="transport_number",
            field=models.CharField(
                blank=True,
                help_text="Номер грузовика, вагона или поезда",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="transport_type",
            field=models.CharField(
                choices=[("TRUCK", "Грузовик"), ("WAGON", "Вагон"), ("TRAIN", "Поезд")],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="AdditionalCraneOperation",
        ),
    ]
