# Generated by Django 5.2.6 on 2025-10-17 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "terminal_operations",
            "0011_containerentry_additional_crane_operation_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerentry",
            name="entry_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
