# Generated by Django 5.2.6 on 2025-12-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_alter_file_options_alter_fileattachment_options_and_more"),
        ("terminal_operations", "0012_alter_containerentry_entry_time"),
        ("vehicles", "0001_add_status_and_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Название компании-владельца контейнера",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-совместимый идентификатор",
                        max_length=250,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Владелец контейнера",
                "verbose_name_plural": "Владельцы контейнеров",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="exit_transport_type",
            field=models.CharField(
                blank=True,
                choices=[("TRUCK", "Авто"), ("WAGON", "Вагон"), ("TRAIN", "Поезд")],
                help_text="Тип транспорта при вывозе",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь (API или менеджер из Telegram), который создал запись",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="transport_number",
            field=models.CharField(
                blank=True, help_text="Номер авто, вагона или поезда", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="transport_type",
            field=models.CharField(
                choices=[("TRUCK", "Авто"), ("WAGON", "Вагон"), ("TRAIN", "Поезд")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="containerentry",
            name="container_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Собственник контейнера",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="terminal_operations.containerowner",
            ),
        ),
        migrations.CreateModel(
            name="CraneOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_date",
                    models.DateTimeField(help_text="Дата и время крановой операции"),
                ),
                (
                    "container_entry",
                    models.ForeignKey(
                        help_text="Запись въезда контейнера",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crane_operations",
                        to="terminal_operations.containerentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Крановая операция",
                "verbose_name_plural": "Крановые операции",
                "ordering": ["-operation_date"],
                "indexes": [
                    models.Index(
                        fields=["container_entry", "-operation_date"],
                        name="crane_op_entry_date_idx",
                    ),
                    models.Index(fields=["-operation_date"], name="crane_op_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plate_number",
                    models.CharField(
                        db_index=True,
                        help_text="Номер автомобиля для сопоставления на воротах",
                        max_length=20,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("LOAD", "Погрузка"), ("UNLOAD", "Разгрузка")],
                        help_text="Тип операции (погрузка/разгрузка)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("MATCHED", "Сопоставлен"),
                            ("COMPLETED", "Завершён"),
                            ("CANCELLED", "Отменён"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Текущий статус заявки",
                        max_length=20,
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время сопоставления на воротах",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="Время отмены заявки клиентом", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Дополнительные примечания от клиента",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Клиент, создавший заявку",
                        limit_choices_to={"user_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Запись въезда контейнера, созданная по этой заявке",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_orders",
                        to="terminal_operations.containerentry",
                    ),
                ),
                (
                    "truck_photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Фото грузовика из заявки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_orders",
                        to="files.file",
                    ),
                ),
                (
                    "vehicle_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Запись въезда автомобиля",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_orders",
                        to="vehicles.vehicleentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предзаказ",
                "verbose_name_plural": "Предзаказы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="preorder_customer_status_idx",
                    ),
                    models.Index(
                        fields=["plate_number", "status"],
                        name="preorder_plate_status_idx",
                    ),
                    models.Index(fields=["-created_at"], name="preorder_created_idx"),
                ],
            },
        ),
    ]
