# Generated by Django 5.2.6 on 2026-01-06 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_bot_access_and_more'),
        ('containers', '0004_alter_container_iso_type'),
        ('files', '0002_alter_file_options_alter_fileattachment_options_and_more'),
        ('terminal_operations', '0013_add_vehicle_entry_fk'),
        ('vehicles', '0001_add_status_and_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerentry',
            name='dwell_time_days',
        ),
        migrations.AddField(
            model_name='containerentry',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания-клиент (необязательно, используйте вместо client_name)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='container_entries', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID группы заявок, созданных одновременно', null=True),
        ),
        migrations.AddIndex(
            model_name='containerentry',
            index=models.Index(fields=['company'], name='company_idx'),
        ),
        migrations.AddIndex(
            model_name='preorder',
            index=models.Index(fields=['batch_id'], name='preorder_batch_idx'),
        ),
    ]
