# Generated by Django 5.2.6 on 2026-01-13 09:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0014_remove_containerentry_dwell_time_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='containerentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='containerowner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='containerowner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='craneoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='craneoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.CreateModel(
            name='ContainerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('zone', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C'), ('D', 'Zone D'), ('E', 'Zone E')], db_index=True, help_text='Зона терминала (A-E)', max_length=1)),
                ('row', models.PositiveSmallIntegerField(help_text='Номер ряда (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bay', models.PositiveSmallIntegerField(help_text='Номер отсека (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tier', models.PositiveSmallIntegerField(help_text='Ярус (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('auto_assigned', models.BooleanField(default=False, help_text='Была ли позиция назначена автоматически')),
                ('container_entry', models.OneToOneField(help_text='Связанная запись въезда контейнера', on_delete=django.db.models.deletion.CASCADE, related_name='position', to='terminal_operations.containerentry')),
            ],
            options={
                'verbose_name': 'Позиция контейнера',
                'verbose_name_plural': 'Позиции контейнеров',
                'ordering': ['zone', 'row', 'bay', 'tier'],
                'indexes': [models.Index(fields=['zone', 'row', 'bay', 'tier'], name='position_coords_idx'), models.Index(fields=['zone'], name='position_zone_idx')],
                'constraints': [models.UniqueConstraint(fields=('zone', 'row', 'bay', 'tier'), name='unique_position', violation_error_message='Эта позиция уже занята другим контейнером')],
            },
        ),
    ]
