# Generated by Django 5.2.6 on 2026-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0015_add_container_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerposition',
            options={'ordering': ['zone', 'row', 'bay', 'tier', 'sub_slot'], 'verbose_name': 'Позиция контейнера', 'verbose_name_plural': 'Позиции контейнеров'},
        ),
        migrations.RemoveConstraint(
            model_name='containerposition',
            name='unique_position',
        ),
        migrations.RemoveIndex(
            model_name='containerposition',
            name='position_coords_idx',
        ),
        migrations.AddField(
            model_name='containerposition',
            name='sub_slot',
            field=models.CharField(choices=[('A', 'Slot A (Left/Front)'), ('B', 'Slot B (Right/Back)')], default='A', help_text='Позиция внутри отсека: A (левая) или B (правая). 40ft контейнеры всегда занимают слот A.', max_length=1),
        ),
        migrations.AddIndex(
            model_name='containerposition',
            index=models.Index(fields=['zone', 'row', 'bay', 'tier', 'sub_slot'], name='position_coords_slot_idx'),
        ),
        migrations.AddConstraint(
            model_name='containerposition',
            constraint=models.UniqueConstraint(fields=('zone', 'row', 'bay', 'tier', 'sub_slot'), name='unique_position_with_slot', violation_error_message='Эта позиция уже занята другим контейнером'),
        ),
    ]
