# Generated by Django 5.2.6 on 2026-01-15 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0016_add_sub_slot_to_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('order_number', models.CharField(db_index=True, help_text='Номер наряда (автогенерируемый)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ASSIGNED', 'Назначен'), ('ACCEPTED', 'Принят'), ('IN_PROGRESS', 'Выполняется'), ('COMPLETED', 'Завершён'), ('VERIFIED', 'Подтверждён'), ('FAILED', 'Ошибка')], db_index=True, default='PENDING', help_text='Текущий статус наряда', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], db_index=True, default='MEDIUM', help_text='Приоритет выполнения', max_length=10)),
                ('target_zone', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C'), ('D', 'Zone D'), ('E', 'Zone E')], help_text='Целевая зона', max_length=1)),
                ('target_row', models.PositiveSmallIntegerField(help_text='Целевой ряд (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('target_bay', models.PositiveSmallIntegerField(help_text='Целевой отсек (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('target_tier', models.PositiveSmallIntegerField(help_text='Целевой ярус (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('target_sub_slot', models.CharField(choices=[('A', 'Slot A (Left/Front)'), ('B', 'Slot B (Right/Back)')], default='A', help_text='Целевая позиция в отсеке', max_length=1)),
                ('sla_deadline', models.DateTimeField(help_text='Крайний срок выполнения')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Время назначения менеджеру', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Время принятия менеджером', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Время начала выполнения', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Время завершения (фото подтверждение)', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Время системной верификации', null=True)),
                ('placement_photo', models.ImageField(blank=True, help_text='Фото подтверждения размещения', null=True, upload_to='work_orders/placement_photos/%Y/%m/')),
                ('verification_status', models.CharField(blank=True, choices=[('PENDING', 'Ожидает проверки'), ('CORRECT', 'Верно'), ('INCORRECT', 'Неверно')], help_text='Результат верификации', max_length=20, null=True)),
                ('verification_notes', models.TextField(blank=True, default='', help_text='Примечания к верификации')),
                ('notes', models.TextField(blank=True, default='', help_text='Дополнительные примечания')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Менеджер, которому назначен наряд', limit_choices_to={'user_type': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('container_entry', models.ForeignKey(help_text='Контейнер для размещения', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='terminal_operations.containerentry')),
                ('created_by', models.ForeignKey(blank=True, help_text='Оператор, создавший наряд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Наряд на размещение',
                'verbose_name_plural': 'Наряды на размещение',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wo_status_created_idx'), models.Index(fields=['assigned_to', 'status'], name='wo_assignee_status_idx'), models.Index(fields=['priority', '-created_at'], name='wo_priority_created_idx'), models.Index(fields=['-sla_deadline'], name='wo_sla_deadline_idx'), models.Index(fields=['order_number'], name='wo_order_number_idx')],
            },
        ),
    ]
