# Generated by Django 5.2.6 on 2026-01-17 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0017_add_work_order_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(help_text='Название/номер техники (например, RS-01, Погрузчик-3)', max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('REACH_STACKER', 'Ричстакер'), ('FORKLIFT', 'Погрузчик'), ('YARD_TRUCK', 'Тягач'), ('RTG_CRANE', 'Козловой кран (RTG)')], db_index=True, help_text='Тип техники', max_length=20)),
                ('license_plate', models.CharField(blank=True, default='', help_text='Госномер (если есть)', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активна ли техника')),
            ],
            options={
                'verbose_name': 'Техника терминала',
                'verbose_name_plural': 'Техника терминала',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='wo_assignee_status_idx',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_to_vehicle',
            field=models.ForeignKey(blank=True, help_text='Техника, которой назначен наряд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='terminal_operations.terminalvehicle'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_to_vehicle', 'status'], name='wo_vehicle_status_idx'),
        ),
    ]
