# Generated by Django 5.2.6 on 2026-01-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0018_add_terminal_vehicle_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalvehicle',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Оператор, работающий на этой технике', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='terminalvehicle',
            index=models.Index(fields=['operator'], name='tv_operator_idx'),
        ),
    ]
