# Generated by Django 5.2.6 on 2026-01-19 09:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0019_add_operator_to_terminal_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Наряд на операцию', 'verbose_name_plural': 'Наряды на операции'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='operation_type',
            field=models.CharField(choices=[('PLACEMENT', 'Размещение'), ('RETRIEVAL', 'Извлечение')], db_index=True, default='PLACEMENT', help_text='Тип операции: размещение контейнера на терминал или извлечение с терминала', max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='container_entry',
            field=models.ForeignKey(help_text='Контейнер для размещения или извлечения', on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='terminal_operations.containerentry'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='target_row',
            field=models.PositiveSmallIntegerField(help_text='Целевой ряд (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['operation_type'], name='wo_operation_type_idx'),
        ),
    ]
