# Generated by Django 5.2.6 on 2026-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0020_add_retrieval_work_orders'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorder',
            name='wo_sla_deadline_idx',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='placement_photo',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='sla_deadline',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Время завершения', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('COMPLETED', 'Завершён')], db_index=True, default='PENDING', help_text='Текущий статус наряда', max_length=20),
        ),
    ]
