# Generated by Django 5.2.6 on 2026-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0022_convert_workorder_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerowner',
            name='notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Уведомления включены'),
        ),
        migrations.AddField(
            model_name='containerowner',
            name='telegram_group_id',
            field=models.CharField(blank=True, help_text='ID группы (-1001234567890) или username (@mygroup)', max_length=50, null=True, verbose_name='Telegram группа'),
        ),
        migrations.AddField(
            model_name='containerowner',
            name='telegram_group_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название группы'),
        ),
    ]
