# Generated by Django 5.2.6 on 2026-01-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0023_add_telegram_notification_to_container_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('event_type', models.CharField(choices=[('ENTRY_CREATED', 'Контейнер принят'), ('STATUS_CHANGED', 'Статус изменён'), ('POSITION_ASSIGNED', 'Позиция назначена'), ('POSITION_REMOVED', 'Позиция освобождена'), ('CRANE_OPERATION', 'Крановая операция'), ('WORK_ORDER_CREATED', 'Наряд создан'), ('WORK_ORDER_COMPLETED', 'Наряд завершён'), ('EXIT_RECORDED', 'Выезд зарегистрирован')], db_index=True, help_text='Тип события', max_length=30)),
                ('event_time', models.DateTimeField(db_index=True, help_text='Время события')),
                ('source', models.CharField(choices=[('API', 'API'), ('TELEGRAM_BOT', 'Telegram бот'), ('EXCEL_IMPORT', 'Импорт Excel'), ('SYSTEM', 'Система')], default='API', help_text='Источник события', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Детали события в формате JSON')),
                ('container_entry', models.ForeignKey(help_text='Запись въезда контейнера', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='terminal_operations.containerentry')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Пользователь, выполнивший действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие контейнера',
                'verbose_name_plural': 'События контейнеров',
                'ordering': ['event_time', 'created_at'],
                'indexes': [models.Index(fields=['container_entry', 'event_time'], name='event_entry_time_idx'), models.Index(fields=['event_type', '-event_time'], name='event_type_time_idx'), models.Index(fields=['-event_time'], name='event_time_desc_idx')],
            },
        ),
    ]
