# Generated by Django 5.2.6 on 2026-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0024_add_container_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerentry',
            name='booking_number',
            field=models.CharField(blank=True, default='', help_text='Номер букинга/заказа', max_length=50),
        ),
        migrations.AddField(
            model_name='containerentry',
            name='imo_class',
            field=models.CharField(blank=True, choices=[('1', 'Класс 1: Взрывчатые вещества'), ('2', 'Класс 2: Газы'), ('3', 'Класс 3: Легковоспламеняющиеся жидкости'), ('4', 'Класс 4: Легковоспламеняющиеся твёрдые вещества'), ('5', 'Класс 5: Окисляющие вещества'), ('6', 'Класс 6: Токсичные вещества'), ('7', 'Класс 7: Радиоактивные материалы'), ('8', 'Класс 8: Коррозионные вещества'), ('9', 'Класс 9: Прочие опасные вещества')], help_text='Класс опасности по классификации IMO (1-9)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='containerentry',
            name='is_hazmat',
            field=models.BooleanField(default=False, help_text='Контейнер содержит опасные грузы'),
        ),
        migrations.AddField(
            model_name='containerentry',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Обычный'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='NORMAL', help_text='Приоритет обработки контейнера', max_length=10),
        ),
        migrations.AddField(
            model_name='containerentry',
            name='vessel_name',
            field=models.CharField(blank=True, default='', help_text='Название судна', max_length=100),
        ),
    ]
