# Generated by Django 5.2.6 on 2026-01-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0025_add_hazmat_priority_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerposition',
            name='container_size',
            field=models.CharField(choices=[('20ft', '20ft'), ('40ft', '40ft'), ('45ft', '45ft')], default='40ft', help_text='Размер контейнерного слота', max_length=10),
        ),
        migrations.AddField(
            model_name='containerposition',
            name='dxf_x',
            field=models.FloatField(blank=True, help_text='Координата X из DXF-чертежа (для 3D отображения)', null=True),
        ),
        migrations.AddField(
            model_name='containerposition',
            name='dxf_y',
            field=models.FloatField(blank=True, help_text='Координата Y из DXF-чертежа (для 3D отображения)', null=True),
        ),
        migrations.AddField(
            model_name='containerposition',
            name='rotation',
            field=models.FloatField(default=0, help_text='Угол поворота в градусах (против часовой от оси X)'),
        ),
        migrations.AlterField(
            model_name='containerposition',
            name='container_entry',
            field=models.OneToOneField(blank=True, help_text='Контейнер, занимающий эту позицию (null = пустой слот)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='terminal_operations.containerentry'),
        ),
    ]
