# Generated by Django 5.2.6 on 2026-02-06 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0026_add_dxf_fields_to_container_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='customer',
            field=models.ForeignKey(help_text='Клиент, создавший заявку', limit_choices_to={'user_type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='container_entry',
            field=models.ForeignKey(help_text='Контейнер для размещения или извлечения', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='terminal_operations.containerentry'),
        ),
    ]
