# Generated by Django 5.2.6 on 2026-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_operations', '0026_add_dxf_fields_to_container_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerentry',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('EMPTY', 'Порожний'), ('LADEN', 'Гружёный')], max_length=10),
        ),
    ]
