# Generated by Django 5.2.6 on 2026-02-09 04:17

from django.db import migrations


def update_laden_42g1_to_dash(apps, schema_editor):
    """
    Reset status and iso_type to "-" for active entries that were
    auto-created from Telegram group messages with default LADEN/42G1 values.
    Operators must manually verify and set correct values.
    """
    ContainerEntry = apps.get_model("terminal_operations", "ContainerEntry")
    Container = apps.get_model("containers", "Container")

    # Find active entries with default group-entry values
    entries = ContainerEntry.objects.filter(
        status="LADEN",
        container__iso_type="42G1",
        exit_date__isnull=True,
    ).select_related("container")

    container_ids = set()
    for entry in entries:
        entry.status = "-"
        entry.save(update_fields=["status"])
        container_ids.add(entry.container_id)

    # Update linked containers
    Container.objects.filter(id__in=container_ids).update(iso_type="-")


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0006_add_dash_choice_for_unverified"),
        ("terminal_operations", "0027_add_dash_choice_for_unverified"),
    ]

    operations = [
        migrations.RunPython(
            update_laden_42g1_to_dash,
            migrations.RunPython.noop,
        ),
    ]
