# Generated by Django 5.2.6 on 2025-12-04 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0002_alter_file_options_alter_fileattachment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Название пункта назначения",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Уникальный код пункта назначения", unique=True
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        default="",
                        help_text="Зона на терминале (K1, K2, H1, и т.д.)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Активен ли этот пункт назначения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт назначения",
                "verbose_name_plural": "Пункты назначения",
                "ordering": ["zone", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Ожидает"),
                            ("ON_TERMINAL", "На терминале"),
                            ("EXITED", "Выехал"),
                            ("CANCELLED", "Отменён"),
                        ],
                        db_index=True,
                        default="ON_TERMINAL",
                        help_text="Текущий статус автомобиля в workflow",
                        max_length=20,
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        db_index=True,
                        help_text="Государственный номер автомобиля",
                        max_length=20,
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="Время въезда на терминал",
                        null=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Легковой автомобиль"),
                            ("CARGO", "Грузовой автомобиль"),
                        ],
                        help_text="Тип транспортного средства",
                        max_length=10,
                    ),
                ),
                (
                    "visitor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYEE", "Сотрудник"),
                            ("CLIENT", "Клиент"),
                            ("GUEST", "Гость"),
                        ],
                        help_text="Тип посетителя (только для легковых автомобилей)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLATFORM", "Платформа"),
                            ("TRUCK", "Фура"),
                            ("TRAILER", "Прицеп"),
                            ("MINI_TRUCK", "Мини-грузовик"),
                            ("ZIL", "ЗИЛ"),
                            ("GAZELLE", "Газель"),
                            ("LABO", "Лабо"),
                        ],
                        help_text="Тип грузового транспорта",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "entry_load_status",
                    models.CharField(
                        blank=True,
                        choices=[("LOADED", "С грузом"), ("EMPTY", "Порожний")],
                        help_text="Статус загрузки при въезде (только для грузовых)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cargo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTAINER", "Контейнер"),
                            ("FOOD", "Продукты питания"),
                            ("METAL", "Металл"),
                            ("WOOD", "Дерево"),
                            ("CHEMICAL", "Химические вещества"),
                            ("EQUIPMENT", "Оборудование"),
                            ("OTHER", "Другое"),
                        ],
                        help_text="Тип перевозимого груза",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "container_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1x20F", "1×20F - Один 20-футовый контейнер"),
                            ("2x20F", "2×20F - Два 20-футовых контейнера"),
                            ("40F", "40F - Один 40-футовый контейнер"),
                        ],
                        help_text="Размер контейнера",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "container_load_status",
                    models.CharField(
                        blank=True,
                        choices=[("LOADED", "С грузом"), ("EMPTY", "Порожний")],
                        help_text="Статус загрузки контейнера (гружёный/порожний)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True, help_text="Время выезда с терминала", null=True
                    ),
                ),
                (
                    "exit_load_status",
                    models.CharField(
                        blank=True,
                        choices=[("LOADED", "С грузом"), ("EMPTY", "Порожний")],
                        help_text="Статус загрузки при выезде (только для грузовых)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Клиент, создавший предзаказ",
                        limit_choices_to={"user_type": "customer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_vehicle_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пункт назначения (включает зону)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_entries",
                        to="vehicles.destination",
                    ),
                ),
                (
                    "entry_photos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Фото автомобиля при въезде (можно несколько)",
                        related_name="vehicle_entry_photos",
                        to="files.file",
                    ),
                ),
                (
                    "exit_photos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Фото автомобиля при выезде (можно несколько)",
                        related_name="vehicle_exit_photos",
                        to="files.file",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, зарегистрировавший въезд",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vehicle_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Въезд транспорта",
                "verbose_name_plural": "Въезды транспорта",
                "ordering": ["-entry_time"],
                "indexes": [
                    models.Index(
                        fields=["license_plate", "-entry_time"],
                        name="vehicles_plate_entry_idx",
                    ),
                    models.Index(
                        fields=["-entry_time"], name="vehicles_entry_time_idx"
                    ),
                    models.Index(
                        fields=["vehicle_type", "-entry_time"],
                        name="vehicles_type_entry_idx",
                    ),
                    models.Index(fields=["exit_time"], name="vehicles_exit_time_idx"),
                    models.Index(
                        fields=["destination", "-entry_time"],
                        name="vehicles_dest_entry_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("exit_time__isnull", True)),
                        fields=("license_plate",),
                        name="unique_active_vehicle_plate",
                        violation_error_message="Автомобиль с таким номером уже находится на терминале",
                    )
                ],
            },
        ),
    ]
