# Generated by Django 5.2.6 on 2026-01-06 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_options_alter_fileattachment_options_and_more'),
        ('vehicles', '0001_add_status_and_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicleentry',
            name='unique_active_vehicle_plate',
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_time',
            field=models.DateTimeField(blank=True, help_text='Время въезда на терминал (заполняется при check-in)', null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicleentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ON_TERMINAL')), fields=('license_plate',), name='unique_active_vehicle_plate', violation_error_message='Автомобиль с таким номером уже находится на терминале'),
        ),
    ]
