# Generated by Django 5.2.6 on 2026-01-27 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_created_at_alter_file_updated_at_and_more'),
        ('vehicles', '0002_remove_vehicleentry_unique_active_vehicle_plate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='cargo_type',
            field=models.CharField(blank=True, choices=[('CONTAINER', 'Контейнер'), ('FOOD', 'Продукты питания'), ('METAL', 'Металл'), ('WOOD', 'Дерево'), ('CHEMICAL', 'Химические вещества'), ('EQUIPMENT', 'Оборудование'), ('OTHER', 'Другое')], help_text='Тип перевозимого груза', max_length=15, null=True, verbose_name='тип груза'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='container_load_status',
            field=models.CharField(blank=True, choices=[('LOADED', 'С грузом'), ('EMPTY', 'Порожний')], help_text='Статус загрузки контейнера (гружёный/порожний)', max_length=10, null=True, verbose_name='загрузка контейнера'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='container_size',
            field=models.CharField(blank=True, choices=[('1x20F', '1×20F - Один 20-футовый контейнер'), ('2x20F', '2×20F - Два 20-футовых контейнера'), ('40F', '40F - Один 40-футовый контейнер')], help_text='Размер контейнера', max_length=10, null=True, verbose_name='размер контейнера'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_load_status',
            field=models.CharField(blank=True, choices=[('LOADED', 'С грузом'), ('EMPTY', 'Порожний')], help_text='Статус загрузки при въезде (только для грузовых)', max_length=10, null=True, verbose_name='загрузка при въезде'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_photos',
            field=models.ManyToManyField(blank=True, help_text='Фото автомобиля при въезде (можно несколько)', related_name='vehicle_entry_photos', to='files.file', verbose_name='фото при въезде'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_time',
            field=models.DateTimeField(blank=True, help_text='Время въезда на терминал (заполняется при check-in)', null=True, verbose_name='время въезда'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='exit_load_status',
            field=models.CharField(blank=True, choices=[('LOADED', 'С грузом'), ('EMPTY', 'Порожний')], help_text='Статус загрузки при выезде (только для грузовых)', max_length=10, null=True, verbose_name='загрузка при выезде'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='exit_photos',
            field=models.ManyToManyField(blank=True, help_text='Фото автомобиля при выезде (можно несколько)', related_name='vehicle_exit_photos', to='files.file', verbose_name='фото при выезде'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='exit_time',
            field=models.DateTimeField(blank=True, help_text='Время выезда с терминала', null=True, verbose_name='время выезда'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='license_plate',
            field=models.CharField(db_index=True, help_text='Государственный номер автомобиля', max_length=20, verbose_name='госномер'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, зарегистрировавший въезд', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vehicle_entries', to=settings.AUTH_USER_MODEL, verbose_name='зарегистрировал'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('PLATFORM', 'Платформа'), ('TRUCK', 'Фура'), ('TRAILER', 'Прицеп'), ('MINI_TRUCK', 'Мини-грузовик'), ('ZIL', 'ЗИЛ'), ('GAZELLE', 'Газель'), ('LABO', 'Лабо')], help_text='Тип грузового транспорта', max_length=15, null=True, verbose_name='тип транспорта'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.CharField(choices=[('LIGHT', 'Легковой автомобиль'), ('CARGO', 'Грузовой автомобиль')], help_text='Тип транспортного средства', max_length=10, verbose_name='тип ТС'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='visitor_type',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', 'Сотрудник'), ('CLIENT', 'Клиент'), ('GUEST', 'Гость')], help_text='Тип посетителя (только для легковых автомобилей)', max_length=10, null=True, verbose_name='тип посетителя'),
        ),
    ]
